server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        add_header X-Secret-Flag "FLAG{http_header_hidden}" always;
        add_header X-Powered-By "NmapTrainingLab/1.0" always;
    }
}
