[global]
  workgroup = CORP
  server string = Corp File Server
  map to guest = Bad User
  log level = 0
  server min protocol = NT1

[public]
  path = /srv/share
  browseable = yes
  read only = yes
  guest ok = yes
