server {
    listen 80;
    root /var/www/html;
    index index.html;

    add_header X-Secret-Flag "FLAG{http_header_hidden}" always;
    add_header X-Powered-By "CorpWeb/2.1" always;
}

server {
    listen 8888;
    root /var/www/html/dev;
    index index.html;

    add_header X-Debug "true" always;
    add_header X-Backend "php-fpm-8.2" always;
}
