options {
    directory "/var/bind";
    listen-on { any; };
    listen-on-v6 { none; };
    allow-query { any; };
    allow-transfer { any; };  // Vulnerable to zone transfers
    recursion yes;
    dnssec-validation no;
};

zone "lab.pivot.local" {
    type master;
    file "db.lab.pivot.local";
};
