server.modules = (
    "mod_access",
    "mod_accesslog",
    "mod_webdav",
    "mod_fastcgi"
)

server.document-root = "/var/www/localhost/webdav"
server.port = 80
server.bind = "0.0.0.0"

server.username = "lighttpd"
server.groupname = "lighttpd"

server.errorlog = "/var/log/lighttpd/error.log"
accesslog.filename = "/var/log/lighttpd/access.log"

mimetype.assign = (
    ".html" => "text/html",
    ".txt" => "text/plain",
    ".php" => "application/x-httpd-php"
)

# WebDAV configuration
$HTTP["url"] =~ "^/webdav($|/)" {
    dir-listing.activate = "enable"
    webdav.activate = "enable"
    webdav.is-readonly = "disable"
}

# PHP FastCGI configuration
fastcgi.server = ( ".php" =>
    ((
        "bin-path" => "/usr/bin/php-cgi83",
        "socket" => "/tmp/php.socket"
    ))
)
