port=5353
listen-address=0.0.0.0
no-resolv
address=/web.corp.local/172.20.1.10
address=/mail.corp.local/172.20.1.20
address=/files.corp.local/172.20.1.30
txt-record=flag.corp.local,"FLAG{dns_txt_record_found}"
txt-record=corp.local,"Corp Lab DNS"
log-queries
